### ISSUE TITLE
More installation information

### ISSUE THREAD

**Issue by TheEnergy** [PaleSkinnySwede/StecaCoolCept#1]
Im not a pro at this. I add the installation manual in HACS.

But what to do from there? 
I have assed to my StecaGrid
"http://192.168.0.251/measurements.xml"
and i edited the .py file with the right information. But how to add it afterwards?

**Comment by TheEnergy** [comment]
Found this in the logs.

Logger: aiohttp.server
Source: components/solarlog/config_flow.py:45
First occurred: 19.34.44 (4 occurrences)
Last logged: 19.34.52

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 277, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/usr/src/homeassistant/homeassistant/components/solarlog/config_flow.py", line 72, in async_step_user
    if await self._test_connection(host):
  File "/usr/src/homeassistant/homeassistant/components/solarlog/config_flow.py", line 45, in _test_connection
    await self.hass.async_add_executor_job(SolarLog, host)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/sunwatcher/solarlog/solarlog.py", line 13, in __init__
    self.time = datetime.strptime(data['time'], '%d.%m.%y %H:%M:%S')
KeyError: 'time'
